/**
 * Konu taksonomisi.
 *
 * MEB kazanimlari ogretim sirasini verir ama ogrenme birimini vermez:
 * bir kazanim cok genis ("problemleri cozebilme"), bir digeri cok dar olabilir.
 * Buradaki konular bizim ogretim birimimizdir; kazanimlara cok-cok baglanir
 * ve aralarinda on kosul grafigi kurar.
 *
 * onKosul alani konu slug'i tasir: `s<sinif>-<slug>`. Grafik dongusuz olmalidir;
 * tohumlama sirasinda dogrulanir.
 */

export interface KonuTohumu {
  /** Sinif seviyesi; hazirlik = 0. */
  sinif: number
  alan: 'geometri' | 'olasilik'
  ad: string
  ozet: string
  /** Bu konunun kapsadigi MEB kazanim kodlari. */
  kazanimlar: string[]
  /** Once ogrenilmesi gereken konularin slug'lari. */
  onKosul?: string[]
  zorluk?: number
}

/** `s5-acilari-olcme` bicimindeki konu slug'ini uretir. */
export function konuSlug(sinif: number, ad: string, slugla: (m: string) => string): string {
  return `s${sinif}-${slugla(ad)}`
}

export const KONULAR: KonuTohumu[] = [
  // ---------------------------------------------------------------- Hazirlik
  {
    sinif: 0,
    alan: 'geometri',
    ad: 'İnşa ve Özel Dörtgenler',
    ozet:
      'Matematiksel araç ve teknolojiyle geometrik kavramların inşası; yamuk, paralelkenar ve eşkenar dörtgen gibi özel dörtgenlerin özelliklerinin keşfi.',
    kazanimlar: ['MAT.H.4.1', 'MAT.H.4.2'],
    zorluk: 3,
  },
  {
    sinif: 0,
    alan: 'geometri',
    ad: 'Fraktallar ve Kaplamalar',
    ozet: 'Yinelemeli desenlerin çözümlenmesi ve geometrik şekillerden düzlem kaplamaları üretme.',
    kazanimlar: ['MAT.H.4.3', 'MAT.H.4.5'],
    zorluk: 3,
  },

  // ----------------------------------------------------------------- 1. sinif
  {
    sinif: 1,
    alan: 'geometri',
    ad: 'Yön, Konum ve Yönergeler',
    ozet:
      'Krokide mesafe ve yön içeren yönergeleri okuma, izleme ve hedefe ulaşan rotayı belirleme.',
    kazanimlar: ['MAT.1.3.1'],
    zorluk: 1,
  },
  {
    sinif: 1,
    alan: 'geometri',
    ad: 'Nesnelerin Eşliği',
    ozet: 'İki nesnenin biçim ve büyüklük bakımından aynı olup olmadığını karşılaştırma.',
    kazanimlar: ['MAT.1.3.2'],
    zorluk: 1,
  },

  // ----------------------------------------------------------------- 2. sinif
  {
    sinif: 2,
    alan: 'geometri',
    ad: 'Geometrik Cisimler ve Şekiller',
    ozet:
      'Günlük yaşamdaki nesneleri küp, prizma, silindir, küre gibi cisimlere ve kare, üçgen, daire gibi şekillere eşleme.',
    kazanimlar: ['MAT.2.3.1', 'MAT.2.3.4'],
    onKosul: ['s1-nesnelerin-esligi'],
    zorluk: 1,
  },
  {
    sinif: 2,
    alan: 'geometri',
    ad: 'Cisim ve Şekillerle Modelleme',
    ozet: 'Geometrik cisim ve şekil modellerini birleştirerek yeni yapılar kurma.',
    kazanimlar: ['MAT.2.3.2', 'MAT.2.3.3'],
    onKosul: ['s2-geometrik-cisimler-ve-sekiller'],
    zorluk: 1,
  },
  {
    sinif: 2,
    alan: 'geometri',
    ad: 'Yön Bulma ve Rota',
    ozet: 'Hedefe ulaşmak için mesafe ve yön içeren stratejiler geliştirme.',
    kazanimlar: ['MAT.2.3.6'],
    onKosul: ['s1-yon-konum-ve-yonergeler'],
    zorluk: 2,
  },
  {
    sinif: 2,
    alan: 'geometri',
    ad: 'Simetriyi Tanıma',
    ozet: 'Verilen şekiller arasından simetrik olanları ayırt etme.',
    kazanimlar: ['MAT.2.3.7'],
    zorluk: 1,
  },
  {
    sinif: 2,
    alan: 'geometri',
    ad: 'Sıvı Ölçme',
    ozet: 'Standart olmayan ölçme araçlarıyla sıvı miktarını tahmin etme ve karşılaştırma.',
    kazanimlar: ['MAT.2.3.5'],
    zorluk: 1,
  },

  // ----------------------------------------------------------------- 3. sinif
  {
    sinif: 3,
    alan: 'geometri',
    ad: 'Geometrik Cisimlerin Özellikleri',
    ozet: 'Cisimlerin yüz, ayrıt ve köşe sayılarını inceleyip yorumlama.',
    kazanimlar: ['MAT.3.3.1'],
    onKosul: ['s2-geometrik-cisimler-ve-sekiller'],
    zorluk: 2,
  },
  {
    sinif: 3,
    alan: 'geometri',
    ad: 'Şekilleri Kenar Sayısına Göre Sınıflandırma',
    ozet: 'Üçgen, dörtgen, beşgen ayrımını kenar sayısı ölçütüyle kurma.',
    kazanimlar: ['MAT.3.3.2'],
    onKosul: ['s2-geometrik-cisimler-ve-sekiller'],
    zorluk: 2,
  },
  {
    sinif: 3,
    alan: 'geometri',
    ad: 'Geometrik Çizim Araçları',
    ozet: 'Cetvel, gönye ve şablonlarla geometrik cisim ve şekilleri çizme.',
    kazanimlar: ['MAT.3.3.3'],
    onKosul: ['s3-sekilleri-kenar-sayisina-gore-siniflandirma'],
    zorluk: 2,
  },
  {
    sinif: 3,
    alan: 'geometri',
    ad: 'Çevre Uzunluğu',
    ozet: 'Şekillerin çevresini standart olmayan ve standart araçlarla tahmin edip ölçme.',
    kazanimlar: ['MAT.3.3.4'],
    zorluk: 2,
  },
  {
    sinif: 3,
    alan: 'geometri',
    ad: 'Simetri Doğruları',
    ozet:
      'Birden fazla simetri doğrusu olan şekilleri çözümleme ve bir parçası verilen simetrik şekli tamamlama.',
    kazanimlar: ['MAT.3.3.6', 'MAT.3.3.7', 'MAT.3.3.8'],
    onKosul: ['s2-simetriyi-tanima'],
    zorluk: 2,
  },
  {
    sinif: 3,
    alan: 'geometri',
    ad: 'Standart Sıvı Ölçüleri',
    ozet: 'Litre ve mililitre cinsinden sıvı miktarını tahmin etme.',
    kazanimlar: ['MAT.3.3.5'],
    onKosul: ['s2-sivi-olcme'],
    zorluk: 2,
  },

  // ----------------------------------------------------------------- 4. sinif
  {
    sinif: 4,
    alan: 'geometri',
    ad: 'Cisimlerin Açınımı',
    ozet: 'Geometrik cisimleri açıp düzlemsel açınımını kurma ve açınımdan cismi geri oluşturma.',
    kazanimlar: ['MAT.4.3.1'],
    onKosul: ['s3-geometrik-cisimlerin-ozellikleri'],
    zorluk: 2,
  },
  {
    sinif: 4,
    alan: 'geometri',
    ad: 'Köşe ve Kenarlar',
    ozet: 'Geometrik şekilleri köşe ve kenar sayısına göre çözümleme.',
    kazanimlar: ['MAT.4.3.2'],
    onKosul: ['s3-sekilleri-kenar-sayisina-gore-siniflandirma'],
    zorluk: 2,
  },
  {
    sinif: 4,
    alan: 'geometri',
    ad: 'Çevre Ölçme',
    ozet: 'Şekillerin çevre uzunluğunu ölçme araçlarıyla belirleme.',
    kazanimlar: ['MAT.4.3.3'],
    onKosul: ['s3-cevre-uzunlugu'],
    zorluk: 2,
  },
  {
    sinif: 4,
    alan: 'geometri',
    ad: 'Alan Tahmini',
    ozet: 'Birim kare sayarak şekillerin alanını tahmin etme.',
    kazanimlar: ['MAT.4.3.4'],
    onKosul: ['s4-kose-ve-kenarlar'],
    zorluk: 2,
  },
  {
    sinif: 4,
    alan: 'geometri',
    ad: 'Açı: Dönme Miktarı',
    ozet: 'Açıyı bir dönme miktarı olarak yorumlama ve ölçme aracının gerekliliğini kavrama.',
    kazanimlar: ['MAT.4.3.5', 'MAT.4.3.6'],
    zorluk: 2,
  },
  {
    sinif: 4,
    alan: 'geometri',
    ad: 'Açı Çeşitleri',
    ozet: 'Dik açıyı ölçüt alarak açıları dar, dik ve geniş olarak sınıflandırma.',
    kazanimlar: ['MAT.4.3.7'],
    onKosul: ['s4-aci-donme-miktari'],
    zorluk: 2,
  },
  {
    sinif: 4,
    alan: 'geometri',
    ad: 'Doğruya Göre Simetri',
    ozet: 'Bir şeklin doğruya göre simetriğini oluşturma ve simetri ilişkisini yorumlama.',
    kazanimlar: ['MAT.4.3.8', 'MAT.4.3.9'],
    onKosul: ['s3-simetri-dogrulari'],
    zorluk: 3,
  },
  {
    sinif: 4,
    alan: 'geometri',
    ad: 'Geometrik Kodlama',
    ozet: 'Bir yapıyı oluşturmak için adım adım kodlama stratejisi kurma.',
    kazanimlar: ['MAT.4.3.10'],
    onKosul: ['s2-yon-bulma-ve-rota'],
    zorluk: 3,
  },
  {
    sinif: 4,
    alan: 'olasilik',
    ad: 'İmkânsız, Olabilir, Kesin',
    ozet: 'Günlük yaşamdaki olayları gerçekleşme durumuna göre üç kategoride değerlendirme.',
    kazanimlar: ['MAT.4.4.1'],
    zorluk: 1,
  },
  {
    sinif: 4,
    alan: 'olasilik',
    ad: 'Veriye Dayalı Araştırma',
    ozet: 'Kategorik ve sayma yoluyla elde edilen veriyi toplama, düzenleme ve yorumlama.',
    kazanimlar: ['MAT.4.4.2'],
    zorluk: 2,
  },

  // --------------------------------------------------------- 5. sinif (pilot)
  {
    sinif: 5,
    alan: 'geometri',
    ad: 'Temel Geometrik Çizimler',
    ozet:
      'Nokta, doğru, doğru parçası, ışın, açı, çember ve dikmeyi pergel, cetvel ve dijital araçlarla çizme; çizim deneyimini yansıtma.',
    kazanimlar: ['MAT.5.3.1', 'MAT.5.3.2'],
    onKosul: ['s3-geometrik-cizim-araclari', 's4-kose-ve-kenarlar'],
    zorluk: 2,
  },
  {
    sinif: 5,
    alan: 'geometri',
    ad: 'Açıları Ölçme',
    ozet: 'İletki ile açı ölçme; ölçme aracının doğru konumlandırılması ve okunması.',
    kazanimlar: ['MAT.5.3.3'],
    onKosul: ['s4-aci-cesitleri'],
    zorluk: 2,
  },
  {
    sinif: 5,
    alan: 'geometri',
    ad: 'Doğruların Durumları ve Açılar',
    ozet:
      'Düzlemde iki veya üç doğrunun birbirine göre durumundan doğan komşu, tümler, bütünler ve ters açılar.',
    kazanimlar: ['MAT.5.3.4'],
    onKosul: ['s5-acilari-olcme', 's5-temel-geometrik-cizimler'],
    zorluk: 3,
  },
  {
    sinif: 5,
    alan: 'geometri',
    ad: 'Çokgenler',
    ozet:
      'Çokgeni ardışık kesişen doğruların kapattığı şekil olarak yorumlama; kenar, köşe ve açı özelliklerini keşfetme.',
    kazanimlar: ['MAT.5.3.5', 'MAT.5.3.6'],
    onKosul: ['s5-temel-geometrik-cizimler'],
    zorluk: 3,
  },
  {
    sinif: 5,
    alan: 'geometri',
    ad: 'Kesişen Çemberler ve Üçgen İnşası',
    ozet:
      'İki noktada kesişen çember çiftinin merkezleri ve kesişim noktasıyla kurulan üçgenler üzerine muhakeme.',
    kazanimlar: ['MAT.5.3.7'],
    onKosul: ['s5-cokgenler', 's5-temel-geometrik-cizimler'],
    zorluk: 4,
  },
  {
    sinif: 5,
    alan: 'geometri',
    ad: 'Dikdörtgenin Çevresi',
    ozet: 'Çevre uzunluğu verilen dikdörtgenin olası kenar uzunluklarını yorumlama.',
    kazanimlar: ['MAT.5.4.1'],
    onKosul: ['s4-cevre-olcme'],
    zorluk: 2,
  },
  {
    sinif: 5,
    alan: 'geometri',
    ad: 'Dikdörtgenin Alanı',
    ozet: 'Birim karelerden yola çıkarak alan bağıntısını kurma; alan ile çevre arasında gidip gelme.',
    kazanimlar: ['MAT.5.4.2', 'MAT.5.4.3'],
    onKosul: ['s4-alan-tahmini', 's5-dikdortgenin-cevresi'],
    zorluk: 3,
  },
  {
    sinif: 5,
    alan: 'geometri',
    ad: 'Çevre ve Alan Problemleri',
    ozet: 'Dikdörtgenin çevresi ve alanıyla modellenen gerçek yaşam problemlerini çözme.',
    kazanimlar: ['MAT.5.4.4'],
    onKosul: ['s5-dikdortgenin-alani'],
    zorluk: 3,
  },
  {
    sinif: 5,
    alan: 'olasilik',
    ad: 'Olasılık Sayı Doğrusu',
    ozet: 'Bir olayın olasılığının 0 ile 1 arasında yer aldığını sayı doğrusu üzerinde kavrama.',
    kazanimlar: ['MAT.5.6.1'],
    onKosul: ['s4-imkansiz-olabilir-kesin'],
    zorluk: 2,
  },
  {
    sinif: 5,
    alan: 'olasilik',
    ad: 'Az ve Çok Olasılıklı Olaylar',
    ozet: 'Aynı deneyin olaylarını olasılıklarına göre karşılaştırma ve sıralama.',
    kazanimlar: ['MAT.5.6.2'],
    onKosul: ['s5-olasilik-sayi-dogrusu'],
    zorluk: 2,
  },

  // ----------------------------------------------------------------- 6. sinif
  {
    sinif: 6,
    alan: 'geometri',
    ad: 'Paralel Doğrular ve Kesen',
    ozet: 'İki paralel doğru ve bir kesenin oluşturduğu yöndeş, iç ters ve dış ters açılar.',
    kazanimlar: ['MAT.6.3.1'],
    onKosul: ['s5-dogrularin-durumlari-ve-acilar'],
    zorluk: 3,
  },
  {
    sinif: 6,
    alan: 'geometri',
    ad: 'İki Kesenle Oluşan Şekiller',
    ozet: 'İki paralel doğrunun iki kesenle oluşturduğu dörtgenlerin özelliklerini inceleme.',
    kazanimlar: ['MAT.6.3.2'],
    onKosul: ['s6-paralel-dogrular-ve-kesen'],
    zorluk: 3,
  },
  {
    sinif: 6,
    alan: 'geometri',
    ad: 'Köşegenlerle Dörtgen İnşası',
    ozet: 'Birbirini ortalayan doğru parçalarını köşegen kabul ederek dörtgen kurma.',
    kazanimlar: ['MAT.6.3.3'],
    onKosul: ['s5-cokgenler'],
    zorluk: 3,
  },
  {
    sinif: 6,
    alan: 'geometri',
    ad: 'Dörtgenlerde Açı Problemleri',
    ozet: 'Üçgen, yamuk, paralelkenar, eşkenar dörtgen, dikdörtgen ve karede açı problemleri.',
    kazanimlar: ['MAT.6.3.4'],
    onKosul: ['s6-kosegenlerle-dortgen-insasi', 's6-iki-kesenle-olusan-sekiller'],
    zorluk: 3,
  },
  {
    sinif: 6,
    alan: 'geometri',
    ad: 'Uzunluk ve Alan Birimleri',
    ozet: 'Uzunluk ve alan ölçme birimleri arasındaki dönüşümlerde analojik akıl yürütme.',
    kazanimlar: ['MAT.6.4.1'],
    onKosul: ['s5-dikdortgenin-alani'],
    zorluk: 2,
  },
  {
    sinif: 6,
    alan: 'geometri',
    ad: 'Paralelkenar ve Üçgenin Alanı',
    ozet: 'Dikdörtgenin alan bağıntısını paralelkenar ve üçgene taşıma.',
    kazanimlar: ['MAT.6.4.2'],
    onKosul: ['s5-dikdortgenin-alani'],
    zorluk: 3,
  },
  {
    sinif: 6,
    alan: 'geometri',
    ad: 'Alan Problemleri',
    ozet: 'Geometrik şekillerin alanıyla modellenen gerçek yaşam durumlarını çözme.',
    kazanimlar: ['MAT.6.4.3'],
    onKosul: ['s6-paralelkenar-ve-ucgenin-alani'],
    zorluk: 3,
  },
  {
    sinif: 6,
    alan: 'geometri',
    ad: 'Çemberin Uzunluğu ve Pi',
    ozet: 'Çevre ile çap arasındaki sabit oranı keşfetme ve çember uzunluğu problemleri.',
    kazanimlar: ['MAT.6.4.4', 'MAT.6.4.5'],
    onKosul: ['s5-temel-geometrik-cizimler'],
    zorluk: 3,
  },
  {
    sinif: 6,
    alan: 'geometri',
    ad: 'Merkez Açı ve Yay',
    ozet: 'Merkez açının ölçüsü ile gördüğü yayın uzunluğu arasındaki orantıyı kurma.',
    kazanimlar: ['MAT.6.4.6'],
    onKosul: ['s6-cemberin-uzunlugu-ve-pi', 's5-acilari-olcme'],
    zorluk: 3,
  },
  {
    sinif: 6,
    alan: 'olasilik',
    ad: 'Gözleme Dayalı Olasılık Tahmini',
    ozet: 'Deney tekrarlarından elde edilen göreli frekansla olasılık tahmini yapma.',
    kazanimlar: ['MAT.6.6.1'],
    onKosul: ['s5-az-ve-cok-olasilikli-olaylar'],
    zorluk: 3,
  },

  // ----------------------------------------------------------------- 7. sinif
  {
    sinif: 7,
    alan: 'geometri',
    ad: 'Yansıma Dönüşümü',
    ozet: 'Şekillerin bir doğruya göre yansımasını oluşturma ve değişmeyenleri belirleme.',
    kazanimlar: ['MAT.7.3.1'],
    onKosul: ['s4-dogruya-gore-simetri'],
    zorluk: 3,
  },
  {
    sinif: 7,
    alan: 'geometri',
    ad: 'Orta Dikme ve Açıortay İnşası',
    ozet: 'Yansıma deneyimini pergel-cetvel ile orta dikme ve açıortay inşasına taşıma.',
    kazanimlar: ['MAT.7.3.2'],
    onKosul: ['s7-yansima-donusumu', 's5-temel-geometrik-cizimler'],
    zorluk: 3,
  },
  {
    sinif: 7,
    alan: 'geometri',
    ad: 'Eş Küplerle Yapılar ve Görünümler',
    ozet: 'Küplerden kurulu yapıların önden, üstten ve yandan görünümlerini ilişkilendirme.',
    kazanimlar: ['MAT.7.4.1'],
    onKosul: ['s4-cisimlerin-acinimi'],
    zorluk: 3,
  },
  {
    sinif: 7,
    alan: 'geometri',
    ad: 'Dikdörtgenler Prizmasının Yüzey Alanı',
    ozet: 'Açınımdan yola çıkarak yüzey alanı bağıntısını kurma.',
    kazanimlar: ['MAT.7.4.2'],
    onKosul: ['s4-cisimlerin-acinimi', 's5-dikdortgenin-alani'],
    zorluk: 3,
  },
  {
    sinif: 7,
    alan: 'geometri',
    ad: 'Dikdörtgenler Prizmasının Hacmi',
    ozet: 'Birim küplerle hacmi yorumlama, bağıntıyı değerlendirme ve hacim birimleri.',
    kazanimlar: ['MAT.7.4.3', 'MAT.7.4.4', 'MAT.7.4.5'],
    onKosul: ['s7-dikdortgenler-prizmasinin-yuzey-alani'],
    zorluk: 3,
  },
  {
    sinif: 7,
    alan: 'geometri',
    ad: 'Prizma Problemleri',
    ozet: 'Dikdörtgenler prizmasıyla modellenen cisimlerde yüzey alanı ve hacim problemleri.',
    kazanimlar: ['MAT.7.4.6'],
    onKosul: ['s7-dikdortgenler-prizmasinin-hacmi'],
    zorluk: 3,
  },
  {
    sinif: 7,
    alan: 'geometri',
    ad: 'Dairenin Alanı',
    ozet: 'Çember uzunluğu ve paralelkenar alanı deneyimini dairenin alan bağıntısına taşıma.',
    kazanimlar: ['MAT.7.4.7'],
    onKosul: ['s6-cemberin-uzunlugu-ve-pi', 's6-paralelkenar-ve-ucgenin-alani'],
    zorluk: 4,
  },
  {
    sinif: 7,
    alan: 'geometri',
    ad: 'Daire Diliminin Alanı',
    ozet: 'Merkez açı - yay ilişkisinden daire ve daire diliminin alanına geçme.',
    kazanimlar: ['MAT.7.4.8'],
    onKosul: ['s7-dairenin-alani', 's6-merkez-aci-ve-yay'],
    zorluk: 4,
  },
  {
    sinif: 7,
    alan: 'geometri',
    ad: 'Eşkenar Dörtgen ve Yamuğun Alanı',
    ozet: 'Köşegen ve yükseklik üzerinden alan bağıntılarını çıkarma.',
    kazanimlar: ['MAT.7.4.9'],
    onKosul: ['s6-paralelkenar-ve-ucgenin-alani'],
    zorluk: 3,
  },
  {
    sinif: 7,
    alan: 'geometri',
    ad: 'Günlük Hayatta Alan Problemleri',
    ozet: 'Daire, daire dilimi, eşkenar dörtgen ve yamuk alanlarıyla gerçek durumları çözme.',
    kazanimlar: ['MAT.7.4.10'],
    onKosul: ['s7-daire-diliminin-alani', 's7-eskenar-dortgen-ve-yamugun-alani'],
    zorluk: 4,
  },
  {
    sinif: 7,
    alan: 'geometri',
    ad: 'Üçgende Yardımcı Elemanlar',
    ozet: 'Kenarortay, açıortay ve yüksekliği inşa ederek çözümleme.',
    kazanimlar: ['MAT.7.5.1', 'MAT.7.5.2'],
    onKosul: ['s7-orta-dikme-ve-aciortay-insasi'],
    zorluk: 4,
  },
  {
    sinif: 7,
    alan: 'olasilik',
    ad: 'Bir Olayın Tümleyeni',
    ozet: 'Bir olay ile tümleyeninin olasılıkları toplamının 1 olduğunu keşfetme.',
    kazanimlar: ['MAT.7.7.1'],
    onKosul: ['s6-gozleme-dayali-olasilik-tahmini'],
    zorluk: 3,
  },
  {
    sinif: 7,
    alan: 'olasilik',
    ad: 'Eşit Olasılıklı Olaylar',
    ozet: 'Aynı deneyin olaylarının eşit olasılıklı olma koşullarını değerlendirme.',
    kazanimlar: ['MAT.7.7.2'],
    onKosul: ['s7-bir-olayin-tumleyeni'],
    zorluk: 3,
  },
  {
    sinif: 7,
    alan: 'olasilik',
    ad: 'Ayrık Olaylar',
    ozet: 'Olayları ayrık olma durumuna göre sınıflandırma ve birleşim olasılığı.',
    kazanimlar: ['MAT.7.7.3'],
    onKosul: ['s7-esit-olasilikli-olaylar'],
    zorluk: 3,
  },

  // ----------------------------------------------------------------- 8. sinif
  {
    sinif: 8,
    alan: 'geometri',
    ad: 'Üçgende Açı-Kenar İlişkisi',
    ozet: 'Büyük açı karşısında büyük kenar ilişkisini dinamik olarak keşfetme.',
    kazanimlar: ['MAT.8.3.1'],
    onKosul: ['s7-ucgende-yardimci-elemanlar'],
    zorluk: 3,
  },
  {
    sinif: 8,
    alan: 'geometri',
    ad: 'Üçgen Eşitsizliği',
    ozet: 'Üçgenin kurulabilmesi için kenar uzunlukları arasındaki koşulu bulma.',
    kazanimlar: ['MAT.8.3.2'],
    onKosul: ['s8-ucgende-aci-kenar-iliskisi'],
    zorluk: 3,
  },
  {
    sinif: 8,
    alan: 'geometri',
    ad: 'Üçgenlerde Eşlik',
    ozet: 'İki üçgenin eş olması için yeterli eleman kümelerini belirleme (KKK, KAK, AKA).',
    kazanimlar: ['MAT.8.3.3'],
    onKosul: ['s8-ucgen-esitsizligi'],
    zorluk: 4,
  },
  {
    sinif: 8,
    alan: 'geometri',
    ad: 'Üçgenlerde Benzerlik',
    ozet: 'Benzerlik için yeterli eleman kümelerini ve benzerlik oranını kurma.',
    kazanimlar: ['MAT.8.3.4'],
    onKosul: ['s8-ucgenlerde-eslik'],
    zorluk: 4,
  },
  {
    sinif: 8,
    alan: 'geometri',
    ad: 'Pisagor Bağıntısı',
    ozet: 'Dik üçgende kenarlar arasındaki bağıntıyı keşfetme ve doğrulama.',
    kazanimlar: ['MAT.8.3.5'],
    onKosul: ['s8-ucgenlerde-benzerlik'],
    zorluk: 4,
  },
  {
    sinif: 8,
    alan: 'geometri',
    ad: 'Üçgen Problemleri',
    ozet: 'Açı-kenar ilişkisi, üçgen eşitsizliği ve Pisagor bağıntısını içeren problemler.',
    kazanimlar: ['MAT.8.3.6'],
    onKosul: ['s8-pisagor-bagintisi'],
    zorluk: 4,
  },
  {
    sinif: 8,
    alan: 'geometri',
    ad: 'Cisimlerin Yüzey Açınımları',
    ozet: 'Dik prizma, piramit, silindir ve koninin açınımlarını çözümleme.',
    kazanimlar: ['MAT.8.4.1'],
    onKosul: ['s7-dikdortgenler-prizmasinin-yuzey-alani'],
    zorluk: 3,
  },
  {
    sinif: 8,
    alan: 'geometri',
    ad: 'Silindirin Yüzey Alanı',
    ozet: 'Açınımdan yola çıkarak dik dairesel silindirin yüzey alanını kurma.',
    kazanimlar: ['MAT.8.4.2'],
    onKosul: ['s8-cisimlerin-yuzey-acinimlari', 's7-dairenin-alani'],
    zorluk: 4,
  },
  {
    sinif: 8,
    alan: 'geometri',
    ad: 'Silindirin Hacmi',
    ozet: 'Daire alanından hareketle silindirin hacim bağıntısını çıkarma.',
    kazanimlar: ['MAT.8.4.3'],
    onKosul: ['s8-silindirin-yuzey-alani', 's7-dikdortgenler-prizmasinin-hacmi'],
    zorluk: 4,
  },
  {
    sinif: 8,
    alan: 'geometri',
    ad: 'Öteleme Dönüşümü',
    ozet: 'Şekilleri belirli bir vektör boyunca öteleme ve değişmeyenleri belirleme.',
    kazanimlar: ['MAT.8.5.1'],
    onKosul: ['s7-yansima-donusumu'],
    zorluk: 3,
  },
  {
    sinif: 8,
    alan: 'geometri',
    ad: 'Koordinat Sisteminde Öteleme',
    ozet: 'Apsis ve ordinatların öteleme altında nasıl değiştiğini çözümleme.',
    kazanimlar: ['MAT.8.5.2'],
    onKosul: ['s8-oteleme-donusumu'],
    zorluk: 4,
  },
  {
    sinif: 8,
    alan: 'geometri',
    ad: 'Dönüşüm Problemleri',
    ozet: 'Öteleme ve yansımayı birlikte içeren problemleri çözme.',
    kazanimlar: ['MAT.8.5.3'],
    onKosul: ['s8-koordinat-sisteminde-oteleme'],
    zorluk: 4,
  },
  {
    sinif: 8,
    alan: 'olasilik',
    ad: 'Olasılık Yaklaşımları',
    ozet: 'Öznel, deneysel ve teorik olasılık yaklaşımlarını ayırt edip seçme.',
    kazanimlar: ['MAT.8.7.1'],
    onKosul: ['s7-ayrik-olaylar'],
    zorluk: 4,
  },

  // ----------------------------------------------------------------- 9. sinif
  {
    sinif: 9,
    alan: 'geometri',
    ad: 'Üçgende Açı ve Kenar Özellikleri',
    ozet: 'Üçgenin açı ve kenar özelliklerini doğrulama ve ilişkilendirme.',
    kazanimlar: ['MAT.9.4.1'],
    onKosul: ['s8-ucgen-problemleri'],
    zorluk: 4,
  },
  {
    sinif: 9,
    alan: 'geometri',
    ad: 'Geometrik Dönüşümler',
    ozet: 'Öteleme, yansıma, döndürme ve bileşkelerini çözümleme.',
    kazanimlar: ['MAT.9.5.1'],
    onKosul: ['s8-donusum-problemleri'],
    zorluk: 4,
  },
  {
    sinif: 9,
    alan: 'geometri',
    ad: 'Eşlik ve Benzerlik Koşulları',
    ozet: 'İki üçgenin eş veya benzer olması için asgari koşullar ve benzer üçgen üretme.',
    kazanimlar: ['MAT.9.5.2', 'MAT.9.5.3'],
    onKosul: ['s8-ucgenlerde-eslik', 's8-ucgenlerde-benzerlik'],
    zorluk: 4,
  },
  {
    sinif: 9,
    alan: 'geometri',
    ad: 'Tales, Öklid ve Pisagor Teoremleri',
    ozet: 'Üç temel teoremi benzerlik üzerinden ispatlama.',
    kazanimlar: ['MAT.9.5.4'],
    onKosul: ['s9-eslik-ve-benzerlik-kosullari', 's8-pisagor-bagintisi'],
    zorluk: 5,
  },
  {
    sinif: 9,
    alan: 'geometri',
    ad: 'Eşlik ve Benzerlik Problemleri',
    ozet: 'Teoremleri ve benzerlik oranını içeren problemleri çözme.',
    kazanimlar: ['MAT.9.5.5'],
    onKosul: ['s9-tales-oklid-ve-pisagor-teoremleri'],
    zorluk: 5,
  },
  {
    sinif: 9,
    alan: 'olasilik',
    ad: 'Gözleme Dayalı Olasılık',
    ozet: 'Çok sayıda deneme ile göreli frekansın teorik olasılığa yakınsamasını gözleme.',
    kazanimlar: ['MAT.9.7.1'],
    onKosul: ['s8-olasilik-yaklasimlari'],
    zorluk: 4,
  },
  {
    sinif: 9,
    alan: 'olasilik',
    ad: 'Olasılıkta Tümevarım',
    ozet: 'Örneklerden yola çıkarak olasılık kurallarına ulaşma.',
    kazanimlar: ['MAT.9.7.2'],
    onKosul: ['s9-gozleme-dayali-olasilik'],
    zorluk: 4,
  },

  // ---------------------------------------------------------------- 10. sinif
  {
    sinif: 10,
    alan: 'geometri',
    ad: 'Dik Üçgende Trigonometrik Oranlar',
    ozet: 'Sinüs, kosinüs, tanjant ve kotanjant oranları ile temel özdeşlikler.',
    kazanimlar: ['MAT.10.4.1'],
    onKosul: ['s9-tales-oklid-ve-pisagor-teoremleri'],
    zorluk: 4,
  },
  {
    sinif: 10,
    alan: 'geometri',
    ad: 'Üçgenin Yardımcı Elemanları',
    ozet: 'Kenarortay, açıortay, yükseklik ve çevrel-iç teğet çemberlerin özellikleri.',
    kazanimlar: ['MAT.10.4.2'],
    onKosul: ['s9-ucgende-aci-ve-kenar-ozellikleri'],
    zorluk: 4,
  },
  {
    sinif: 10,
    alan: 'geometri',
    ad: 'Üçgenin Alanı ve Değişimi',
    ozet: 'Taban ve yükseklik değişiminin alana etkisini dinamik olarak inceleme.',
    kazanimlar: ['MAT.10.4.3'],
    onKosul: ['s10-ucgenin-yardimci-elemanlari'],
    zorluk: 4,
  },
  {
    sinif: 10,
    alan: 'geometri',
    ad: 'Sinüs ve Kosinüs Teoremleri',
    ozet: 'Herhangi bir üçgende kenar-açı ilişkilerini veren iki teoremi ispatlama.',
    kazanimlar: ['MAT.10.4.4'],
    onKosul: ['s10-dik-ucgende-trigonometrik-oranlar'],
    zorluk: 5,
  },
  {
    sinif: 10,
    alan: 'geometri',
    ad: 'Koordinat Sisteminde Uzaklık ve Bölme',
    ozet: 'İki nokta arası uzaklık ve bir doğru parçasını belli oranda bölen nokta.',
    kazanimlar: ['MAT.10.5.1'],
    onKosul: ['s8-koordinat-sisteminde-oteleme'],
    zorluk: 4,
  },
  {
    sinif: 10,
    alan: 'geometri',
    ad: 'Analitik Düzlemde Doğru',
    ozet: 'Eğim, doğru denklemi, paralellik-diklik ve doğru problemleri.',
    kazanimlar: ['MAT.10.5.2'],
    onKosul: ['s10-koordinat-sisteminde-uzaklik-ve-bolme'],
    zorluk: 5,
  },
  {
    sinif: 10,
    alan: 'olasilik',
    ad: 'Koşullu Olasılık',
    ozet: 'Bir olayın bilinmesinin diğerinin olasılığını nasıl değiştirdiğini çözümleme.',
    kazanimlar: ['MAT.10.7.1'],
    onKosul: ['s9-olasilikta-tumevarim'],
    zorluk: 5,
  },
  {
    sinif: 10,
    alan: 'olasilik',
    ad: 'Bağımlı ve Bağımsız Olaylar',
    ozet: 'Ardışık olayların birbirine bağlı olduğu durumlarda olasılık hesabı.',
    kazanimlar: ['MAT.10.7.2'],
    onKosul: ['s10-kosullu-olasilik'],
    zorluk: 5,
  },

  // ---------------------------------------------------------------- 11. sinif
  {
    sinif: 11,
    alan: 'geometri',
    ad: 'Dörtgenlerin Özellikleri',
    ozet: 'Üçgen özelliklerinden yola çıkarak dörtgenlerin açı, kenar, köşegen ve simetrisi.',
    kazanimlar: ['MAT.11.2.1', 'MAT.11.2.2'],
    onKosul: ['s6-dortgenlerde-aci-problemleri', 's9-eslik-ve-benzerlik-problemleri'],
    zorluk: 4,
  },
  {
    sinif: 11,
    alan: 'geometri',
    ad: 'İçbükey ve Dışbükey Çokgenler',
    ozet: 'Çokgenleri bükeylik ölçütüne göre sınıflandırma.',
    kazanimlar: ['MAT.11.2.3'],
    onKosul: ['s5-cokgenler'],
    zorluk: 3,
  },
  {
    sinif: 11,
    alan: 'geometri',
    ad: 'Dışbükey Çokgenlerin Özellikleri',
    ozet: 'Kenar, açı, köşegen, simetri ve alan özelliklerine dair çıkarım.',
    kazanimlar: ['MAT.11.2.4'],
    onKosul: ['s11-icbukey-ve-disbukey-cokgenler', 's11-dortgenlerin-ozellikleri'],
    zorluk: 4,
  },
  {
    sinif: 11,
    alan: 'geometri',
    ad: 'Çokgen Problemleri',
    ozet: 'Çokgen özelliklerini içeren problemleri çözme.',
    kazanimlar: ['MAT.11.2.5'],
    onKosul: ['s11-disbukey-cokgenlerin-ozellikleri'],
    zorluk: 5,
  },

  // ---------------------------------------------------------------- 12. sinif
  {
    sinif: 12,
    alan: 'geometri',
    ad: 'Çemberin Elemanları',
    ozet: 'Kesen, kiriş, teğet, çap ve yayı çözümleme.',
    kazanimlar: ['MAT.12.3.1'],
    onKosul: ['s6-merkez-aci-ve-yay'],
    zorluk: 4,
  },
  {
    sinif: 12,
    alan: 'geometri',
    ad: 'Çemberde Açı, Kiriş ve Teğet',
    ozet: 'Çevre açı, iç açı, dış açı ve teğet-kiriş açı özellikleri.',
    kazanimlar: ['MAT.12.3.2'],
    onKosul: ['s12-cemberin-elemanlari'],
    zorluk: 5,
  },
  {
    sinif: 12,
    alan: 'geometri',
    ad: 'Çember ve Daire Problemleri',
    ozet: 'Çember özellikleri ve daire alanını birlikte kullanan problemler.',
    kazanimlar: ['MAT.12.3.3'],
    onKosul: ['s12-cemberde-aci-kiris-ve-teget', 's7-dairenin-alani'],
    zorluk: 5,
  },
  {
    sinif: 12,
    alan: 'geometri',
    ad: 'Dik Prizma ve Silindir',
    ozet: 'Dik prizma ve dik dairesel silindirin elemanlarını çözümleme.',
    kazanimlar: ['MAT.12.4.1'],
    onKosul: ['s8-silindirin-hacmi'],
    zorluk: 4,
  },
  {
    sinif: 12,
    alan: 'geometri',
    ad: 'Piramit, Koni ve Küre',
    ozet: 'Dik piramit, dik dairesel koni ve kürenin elemanları ve bağıntıları.',
    kazanimlar: ['MAT.12.4.2'],
    onKosul: ['s12-dik-prizma-ve-silindir'],
    zorluk: 5,
  },
  {
    sinif: 12,
    alan: 'geometri',
    ad: 'Yüzey Alanı ve Hacim Problemleri',
    ozet: 'Geometrik cisimlerin yüzey alanı ve hacim bağıntılarıyla optimizasyon problemleri.',
    kazanimlar: ['MAT.12.4.3'],
    onKosul: ['s12-piramit-koni-ve-kure'],
    zorluk: 5,
  },
]
