/**
 * 3. ve 4. sinif geometri - on dort sahne.
 *
 * Bu yaslarda da koordinat duzlemi yok; sayma ve olcme izgara uzerinden
 * yuruyor. Aci konusu 4. sinifta giriyor, bu yuzden ilk kez burada
 * olcum_aci kullaniliyor.
 *
 * Calistir: npm run icerik-ilk2 -w @matgebra/mcp
 */
import {
  aci,
  adim,
  ayar,
  baglan,
  bilesen,
  cember,
  cizgi,
  cokgen,
  duzgunKoseler,
  izdusum,
  metin,
  nokta,
  olcumKaynakli,
  otelenmisCokgen,
  oteleme,
  surgu,
  uret,
  uzunluk,
  yansima,
} from './icerik-ortak.mjs'

const { istemci, cagir } = await baglan('icerik-ilk2')

/* --------------------------------------------------------- 3. sinif */

const KUP_ACINIM = {
  slug: 'kup-yuz-kose-ayrit',
  konuSlug: 's3-geometrik-cisimlerin-ozellikleri',
  tur: 'kesif',
  baslik: 'Küpün yüzleri, köşeleri, ayrıtları',
  ozet:
    'Küpü açıp düzleştirdik: altı kare çıktı. Her kare bir yüz. Sayarak küpün kaç yüzü, kaç köşesi, kaç ayrıtı olduğunu bulun.',
  zorluk: 2,
  sira: 1,
  durum: 'yayin',
  ayar: ayar('izgara', [-10, 9, 10, -9]),
  nesneler: [
    nokta('A', -2, -6, 0, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('B', 1, -6, 1, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('C', 1, -3, 2, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('D', -2, -3, 3, { surukleme: 'yok', rol: 'notr', etiket: null }),
    cokgen('y1', ['A', 'B', 'C', 'D'], 4, { rol: 'nane', opaklik: 0.55 }),
    ...otelenmisCokgen('y2', ['A', 'B', 'C', 'D'], 0, 3, 5, { rol: 'gok', opaklik: 0.55 }),
    ...otelenmisCokgen('y3', ['A', 'B', 'C', 'D'], 0, 6, 10, { rol: 'nane', opaklik: 0.55 }),
    ...otelenmisCokgen('y4', ['A', 'B', 'C', 'D'], 0, 9, 15, { rol: 'gok', opaklik: 0.55 }),
    ...otelenmisCokgen('y5', ['A', 'B', 'C', 'D'], -3, 3, 20, { rol: 'seftali', opaklik: 0.55 }),
    ...otelenmisCokgen('y6', ['A', 'B', 'C', 'D'], 3, 3, 25, { rol: 'seftali', opaklik: 0.55 }),
    metin('yazi', -6, -7.5, 'küpün açınımı: 6 kare', 30, { rol: 'notr' }),
  ],
  adimlar: [
    adim(1, 'Altı kare', 'Küpü makasla kesip düzleştirirsek bu şekil çıkar. Kareleri sayın: altı tane.', ['y1', 'y2', 'y3', 'y4', 'y5', 'y6']),
    adim(2, 'Her kare bir yüz', 'Küpün 6 yüzü vardır. Bu şekli katlarsanız kutu oluşur.', ['yazi']),
    adim(3, 'Köşeleri sayın', 'Kapalı küpün 8 köşesi vardır: altta dört, üstte dört.', ['y1']),
    adim(4, 'Ayrıtlar', 'İki yüzün birleştiği çizgilere ayrıt denir. Küpte 12 ayrıt vardır.', ['y3']),
  ],
}

const KENAR_SAYISI = {
  slug: 'kenar-sayisina-gore',
  konuSlug: 's3-sekilleri-kenar-sayisina-gore-siniflandirma',
  tur: 'kesif',
  baslik: 'Kenar sayısına göre şekiller',
  ozet:
    'Üçgen, dörtgen, beşgen, altıgen. Adları kenar sayısından geliyor. Her şeklin köşesini sürükleyip biçimini bozun: adı değişmiyor.',
  zorluk: 2,
  sira: 1,
  durum: 'yayin',
  ayar: ayar('izgara', [-13, 7, 13, -8]),
  nesneler: [
    nokta('U1', -11, -4, 0, { rol: 'seftali', etiket: null }),
    nokta('U2', -7, -4, 1, { surukleme: 'yok', rol: 'seftali', etiket: null }),
    nokta('U3', -9, 0, 2, { surukleme: 'yok', rol: 'seftali', etiket: null }),
    cokgen('ucgen', ['U1', 'U2', 'U3'], 3, { rol: 'seftali', opaklik: 0.6 }),
    metin('ucgenAd', -9, -5.6, 'üçgen (3)', 4, { rol: 'seftali' }),
    nokta('D1', -5, -4, 5, { rol: 'nane', etiket: null }),
    nokta('D2', -1, -4, 6, { surukleme: 'yok', rol: 'nane', etiket: null }),
    nokta('D3', -1, 0, 7, { surukleme: 'yok', rol: 'nane', etiket: null }),
    nokta('D4', -5, 0, 8, { surukleme: 'yok', rol: 'nane', etiket: null }),
    cokgen('dortgen', ['D1', 'D2', 'D3', 'D4'], 9, { rol: 'nane', opaklik: 0.6 }),
    metin('dortgenAd', -3, -5.6, 'dörtgen (4)', 10, { rol: 'nane' }),
    nokta('Obes', 3, -2, 11, { surukleme: 'yok', rol: 'notr', etiket: null, gorunur: false }),
    nokta('P0', 5.5, -2, 12, { rol: 'gok', etiket: null }),
    ...duzgunKoseler('P', 'Obes', 'P0', 5, 13, { rol: 'gok', etiketli: false }).nesneler,
    cokgen('besgen', duzgunKoseler('P', 'Obes', 'P0', 5, 13).adlar, 17, {
      rol: 'gok',
      opaklik: 0.6,
    }),
    metin('besgenAd', 3, -5.6, 'beşgen (5)', 18, { rol: 'gok' }),
    nokta('Oalti', 10, -2, 19, { surukleme: 'yok', rol: 'notr', etiket: null, gorunur: false }),
    nokta('H0', 12.5, -2, 20, { rol: 'gul', etiket: null }),
    ...duzgunKoseler('H', 'Oalti', 'H0', 6, 21, { rol: 'gul', etiketli: false }).nesneler,
    cokgen('altigen', duzgunKoseler('H', 'Oalti', 'H0', 6, 21).adlar, 26, {
      rol: 'gul',
      opaklik: 0.6,
    }),
    metin('altigenAd', 10, -5.6, 'altıgen (6)', 27, { rol: 'gul' }),
  ],
  adimlar: [
    adim(1, 'Kenarları sayın', 'Soldan sağa: üç, dört, beş, altı kenar.', ['ucgen', 'dortgen', 'besgen', 'altigen']),
    adim(2, 'Ad kenar sayısından gelir', 'Üçgen üç kenarlı, dörtgen dört kenarlı demek. Beş kenarlıya beşgen, altı kenarlıya altıgen denir.', ['ucgenAd', 'dortgenAd', 'besgenAd', 'altigenAd']),
    adim(3, 'Köşe sayısı da aynı', 'Her şekilde kenar sayısı ile köşe sayısı eşittir. Sayıp kontrol edin.', ['dortgen', 'besgen']),
    adim(4, 'Biçim değişse de ad değişmez', 'Turuncu ve yeşil şekillerin köşelerini sürükleyin. Şekil çarpılıyor ama kenar sayısı aynı kaldığı için adı da aynı kalıyor.', ['U1', 'D1']),
  ],
}

const CIZIM_ARACLARI = {
  slug: 'cetvel-ve-gonye',
  konuSlug: 's3-geometrik-cizim-araclari',
  tur: 'kesif',
  baslik: 'Cetvel ve gönye ne işe yarar?',
  ozet:
    'Cetvel uzunluk ölçer, gönye dik açı çizer. İkisini birlikte kullanarak bir dikdörtgen kurulur.',
  zorluk: 2,
  sira: 1,
  durum: 'yayin',
  ayar: ayar('izgara', [-10, 8, 10, -8]),
  nesneler: [
    // Iki surgu de dogru PARCASI uzerinde: B, A'nin soluna gecemiyor,
    // C de B'nin altina inemiyor. Boylece gonye acisi hicbir surukleyiste
    // donuk aciya donusmuyor.
    nokta('A', -7, -5, 0, { surukleme: 'yok', rol: 'notr', etiket: 'A' }),
    nokta('Z', 8, -5, 1, { surukleme: 'yok', rol: 'notr', etiket: null, gorunur: false }),
    // Ray A'nin iki birim sagindan basliyor: B, A'ya oturup ucgeni
    // sifirlayamiyor.
    oteleme('Rbas', 'A', 2, 0, 2, { rol: 'notr', etiket: null, gorunur: false }),
    cizgi('ray', 'dogru_parcasi', 'Rbas', 'Z', 3, { rol: 'notr', kalinlik: 1, cizgiTipi: 'noktali' }),
    surgu('B', 'ray', 2, -5, 4, { rol: 'gok', etiket: 'B' }),
    cizgi('taban', 'dogru_parcasi', 'A', 'B', 5, { rol: 'gok', kalinlik: 4 }),
    uzunluk('tabanOlcu', 'A', 'B', 6, { rol: 'gok', etiket: 'cetvelle ölçülen' }),
    // Dik ray da B'nin bir birim ustunden basliyor.
    oteleme('Balt', 'B', 0, 1, 7, { rol: 'notr', etiket: null, gorunur: false }),
    oteleme('Bust', 'B', 0, 9, 8, { rol: 'notr', etiket: null, gorunur: false }),
    cizgi('dikRay', 'dogru_parcasi', 'Balt', 'Bust', 9, {
      rol: 'notr',
      kalinlik: 1,
      cizgiTipi: 'noktali',
    }),
    surgu('C', 'dikRay', 2, 3, 10, { rol: 'seftali', etiket: 'C' }),
    cizgi('dikKenar', 'dogru_parcasi', 'B', 'C', 11, { rol: 'seftali', kalinlik: 4 }),
    aci('gonyeAcisi', 'C', 'B', 'A', 12, { rol: 'tereyagi' }),
    bilesen('D', 'A', 'C', 13, { rol: 'notr', etiket: 'D' }),
    cokgen('dikdortgen', ['A', 'B', 'C', 'D'], 14, { rol: 'nane', opaklik: 0.4 }),
    metin('bilgi', -3, 6.5, 'cetvel: uzunluk — gönye: dik açı', 15, { rol: 'notr' }),
  ],
  adimlar: [
    adim(1, 'Cetvelle bir doğru parçası', 'A ile B arasına düz bir çizgi çekildi. Cetvel hem düz çizmeye hem uzunluk ölçmeye yarar.', ['taban', 'tabanOlcu']),
    adim(2, 'Gönyeyle dik açı', 'B köşesinden yukarı doğru dik bir kenar çizildi. Sarı işaret açının 90 derece olduğunu gösteriyor.', ['dikKenar', 'gonyeAcisi']),
    adim(3, 'Dördüncü köşe', 'Karşı kenarları tamamlayınca dikdörtgen çıkıyor.', ['dikdortgen']),
    adim(4, 'Kendiniz deneyin', 'B ve C noktalarını sürükleyerek farklı boyutta dikdörtgenler kurun. Dik açı hiç bozulmuyor.', ['B', 'C', 'gonyeAcisi']),
  ],
}

const CEVRE3 = {
  slug: 'cevre-uzunlugu-sayarak',
  konuSlug: 's3-cevre-uzunlugu',
  tur: 'kesif',
  baslik: 'Çevre: etrafını dolaşmak',
  ozet:
    'Şeklin etrafında bir tur atın ve geçtiğiniz kutucukları sayın. Bulduğunuz sayı çevredir.',
  zorluk: 2,
  sira: 1,
  durum: 'yayin',
  ayar: ayar('izgara', [-10, 8, 10, -8]),
  nesneler: [
    nokta('K1', -7, -5, 0, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('K3', 0, 1, 1, { rol: 'seftali', etiket: 'sürükle' }),
    bilesen('K2', 'K3', 'K1', 2, { rol: 'notr', etiket: null, gorunur: false }),
    bilesen('K4', 'K1', 'K3', 3, { rol: 'notr', etiket: null, gorunur: false }),
    cokgen('dortgen', ['K1', 'K2', 'K3', 'K4'], 4, { rol: 'nane', opaklik: 0.45 }),
    uzunluk('k1', 'K1', 'K2', 5, { rol: 'gok', etiket: 'alt' }),
    uzunluk('k2', 'K2', 'K3', 6, { rol: 'gul', etiket: 'sağ' }),
    uzunluk('k3', 'K3', 'K4', 7, { rol: 'gok', etiket: 'üst' }),
    uzunluk('k4', 'K4', 'K1', 8, { rol: 'gul', etiket: 'sol' }),
    olcumKaynakli('cevre', 'olcum_cevre', 'dortgen', 9, { rol: 'lavanta' }),
  ],
  adimlar: [
    adim(1, 'Dört kenar', 'Alt, sağ, üst, sol. Her kenarın uzunluğu ekranda yazıyor.', ['k1', 'k2', 'k3', 'k4']),
    adim(2, 'Toplayın', 'Dört sayıyı toplayın. Çıkan sonuç mor kutudaki çevre ile aynı olmalı.', ['cevre']),
    adim(3, 'Karşılıklı kenarlar eşit', 'Alt ile üst aynı, sağ ile sol aynı. O yüzden çevre için (alt + sağ) × 2 de yeter.', ['k1', 'k3', 'k2', 'k4']),
    adim(4, 'Büyütün küçültün', 'Turuncu köşeyi sürükleyin. Şekil büyüdükçe çevre de büyüyor.', ['K3', 'cevre']),
  ],
}

const SIMETRI_DOGRULARI = {
  slug: 'kac-simetri-dogrusu',
  konuSlug: 's3-simetri-dogrulari',
  tur: 'kesif',
  baslik: 'Bir şeklin kaç simetri doğrusu var?',
  ozet:
    'Kareyi ikiye katlayabileceğiniz dört ayrı çizgi var. Dikdörtgende sadece iki, eşkenar üçgende üç tane.',
  zorluk: 3,
  sira: 1,
  durum: 'yayin',
  ayar: ayar('yok', [-12, 8, 12, -8]),
  nesneler: [
    nokta('K1', -10, -3, 0, { surukleme: 'yok', rol: 'nane', etiket: null }),
    nokta('K2', -4, -3, 1, { surukleme: 'yok', rol: 'nane', etiket: null }),
    nokta('K3', -4, 3, 2, { surukleme: 'yok', rol: 'nane', etiket: null }),
    nokta('K4', -10, 3, 3, { surukleme: 'yok', rol: 'nane', etiket: null }),
    cokgen('kare', ['K1', 'K2', 'K3', 'K4'], 4, { rol: 'nane', opaklik: 0.45 }),
    nokta('Sd1', -7, -4, 5, { surukleme: 'yok', rol: 'notr', etiket: null, gorunur: false }),
    nokta('Sd2', -7, 4, 6, { surukleme: 'yok', rol: 'notr', etiket: null, gorunur: false }),
    cizgi('kareDusey', 'dogru_parcasi', 'Sd1', 'Sd2', 7, { rol: 'gul', kalinlik: 2, cizgiTipi: 'kesik' }),
    nokta('Sy1', -11, 0, 8, { surukleme: 'yok', rol: 'notr', etiket: null, gorunur: false }),
    nokta('Sy2', -3, 0, 9, { surukleme: 'yok', rol: 'notr', etiket: null, gorunur: false }),
    cizgi('kareYatay', 'dogru_parcasi', 'Sy1', 'Sy2', 10, { rol: 'gul', kalinlik: 2, cizgiTipi: 'kesik' }),
    cizgi('kareCapraz1', 'dogru_parcasi', 'K1', 'K3', 11, { rol: 'gul', kalinlik: 2, cizgiTipi: 'kesik' }),
    cizgi('kareCapraz2', 'dogru_parcasi', 'K2', 'K4', 12, { rol: 'gul', kalinlik: 2, cizgiTipi: 'kesik' }),
    metin('kareAd', -7, -4.8, 'kare: 4 simetri doğrusu', 13, { rol: 'nane' }),
    nokta('D1', 2, -2, 14, { surukleme: 'yok', rol: 'gok', etiket: null }),
    nokta('D2', 10, -2, 15, { surukleme: 'yok', rol: 'gok', etiket: null }),
    nokta('D3', 10, 2, 16, { surukleme: 'yok', rol: 'gok', etiket: null }),
    nokta('D4', 2, 2, 17, { surukleme: 'yok', rol: 'gok', etiket: null }),
    cokgen('dikdortgen', ['D1', 'D2', 'D3', 'D4'], 18, { rol: 'gok', opaklik: 0.45 }),
    nokta('Dd1', 6, -3, 19, { surukleme: 'yok', rol: 'notr', etiket: null, gorunur: false }),
    nokta('Dd2', 6, 3, 20, { surukleme: 'yok', rol: 'notr', etiket: null, gorunur: false }),
    cizgi('dikDusey', 'dogru_parcasi', 'Dd1', 'Dd2', 21, { rol: 'gul', kalinlik: 2, cizgiTipi: 'kesik' }),
    nokta('Dy1', 1, 0, 22, { surukleme: 'yok', rol: 'notr', etiket: null, gorunur: false }),
    nokta('Dy2', 11, 0, 23, { surukleme: 'yok', rol: 'notr', etiket: null, gorunur: false }),
    cizgi('dikYatay', 'dogru_parcasi', 'Dy1', 'Dy2', 24, { rol: 'gul', kalinlik: 2, cizgiTipi: 'kesik' }),
    metin('dikAd', 6, -4.8, 'dikdörtgen: 2 simetri doğrusu', 25, { rol: 'gok' }),
  ],
  adimlar: [
    adim(1, 'Katlama çizgisi', 'Bir şekli bir çizgiden katladığınızda iki yarı tam üst üste geliyorsa o çizgi simetri doğrusudur.', ['kare', 'kareDusey']),
    adim(2, 'Karede dört tane', 'Dikey, yatay ve iki köşegen. Dördü de kareyi tam ikiye katlar.', ['kareDusey', 'kareYatay', 'kareCapraz1', 'kareCapraz2']),
    adim(3, 'Dikdörtgende iki tane', 'Dikdörtgende sadece dikey ve yatay çizgi işe yarar. Köşegenden katlarsanız yarılar üst üste gelmez.', ['dikDusey', 'dikYatay']),
    adim(4, 'Neden fark var?', 'Karenin dört kenarı eşit olduğu için daha çok katlama yolu var. Dikdörtgende en ile boy farklı olduğundan köşegen işe yaramıyor.', ['kareAd', 'dikAd']),
  ],
}

const LITRE = {
  slug: 'litre-ve-mililitre',
  konuSlug: 's3-standart-sivi-olculeri',
  tur: 'gercek_hayat',
  baslik: 'Litre ve mililitre',
  ozet:
    '1 litrelik şişe, 250 mililitrelik bardaklara bölündü. Dört bardak bir litre eder.',
  zorluk: 2,
  sira: 1,
  durum: 'yayin',
  ayar: ayar('izgara', [-10, 9, 10, -9]),
  nesneler: [
    nokta('S1', -7, -6, 0, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('S2', -3, -6, 1, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('S3', -3, 6, 2, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('S4', -7, 6, 3, { surukleme: 'yok', rol: 'notr', etiket: null }),
    cokgen('sise', ['S1', 'S2', 'S3', 'S4'], 4, { rol: 'gok', opaklik: 0.4 }),
    metin('siseAd', -5, -7.3, '1 litre', 5, { rol: 'gok' }),
    nokta('B1', 2, -6, 6, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('B2', 6, -6, 7, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('B3', 6, -3, 8, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('B4', 2, -3, 9, { surukleme: 'yok', rol: 'notr', etiket: null }),
    cokgen('bardak1', ['B1', 'B2', 'B3', 'B4'], 10, { rol: 'seftali', opaklik: 0.55 }),
    ...otelenmisCokgen('bardak2', ['B1', 'B2', 'B3', 'B4'], 0, 3, 11, {
      rol: 'seftali',
      opaklik: 0.55,
    }),
    ...otelenmisCokgen('bardak3', ['B1', 'B2', 'B3', 'B4'], 0, 6, 16, {
      rol: 'seftali',
      opaklik: 0.55,
    }),
    ...otelenmisCokgen('bardak4', ['B1', 'B2', 'B3', 'B4'], 0, 9, 21, {
      rol: 'seftali',
      opaklik: 0.55,
    }),
    metin('bardakAd', 4, -7.3, '4 × 250 mL', 26, { rol: 'seftali' }),
    metin('esitlik', -0.5, 7.6, '1 L = 1000 mL', 27, { rol: 'gul' }),
  ],
  adimlar: [
    adim(1, 'Bir litrelik şişe', 'Soldaki mavi şişe 1 litre alıyor.', ['sise', 'siseAd']),
    adim(2, 'Dört bardak', 'Sağdaki turuncu bardakların her biri 250 mililitre. Dördünü üst üste koyduk.', ['bardak1', 'bardak2', 'bardak3', 'bardak4']),
    adim(3, 'Yükseklikleri aynı', 'Dört bardağın toplam yüksekliği şişeninkine eşit. Demek ki dört bardak bir şişe eder.', ['sise', 'bardak4']),
    adim(4, 'Sayıyla', '250 + 250 + 250 + 250 = 1000. Yani 1 litre 1000 mililitredir.', ['esitlik']),
  ],
}

/* --------------------------------------------------------- 4. sinif */

const ACINIM4 = {
  slug: 'kutu-acinimi',
  konuSlug: 's4-cisimlerin-acinimi',
  tur: 'gercek_hayat',
  baslik: 'Kutuyu açarsak ne çıkar?',
  ozet:
    'Bir diş macunu kutusunu keserek düzleştirin: altı dikdörtgen çıkar. Karşılıklı yüzler birbirinin aynısı.',
  zorluk: 3,
  sira: 1,
  durum: 'yayin',
  ayar: ayar('izgara', [-12, 9, 12, -9]),
  nesneler: [
    nokta('A', -3, -6, 0, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('B', 1, -6, 1, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('C', 1, -3, 2, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('D', -3, -3, 3, { surukleme: 'yok', rol: 'notr', etiket: null }),
    cokgen('on', ['A', 'B', 'C', 'D'], 4, { rol: 'nane', opaklik: 0.55, etiket: 'ön' }),
    ...otelenmisCokgen('arka', ['A', 'B', 'C', 'D'], 0, 6, 5, {
      rol: 'nane',
      opaklik: 0.55,
      etiket: 'arka',
    }),
    ...otelenmisCokgen('ust', ['A', 'B', 'C', 'D'], 0, 3, 10, {
      rol: 'gok',
      opaklik: 0.55,
      etiket: 'üst',
    }),
    ...otelenmisCokgen('alt', ['A', 'B', 'C', 'D'], 0, 9, 15, {
      rol: 'gok',
      opaklik: 0.55,
      etiket: 'alt',
    }),
    ...otelenmisCokgen('sol', ['A', 'B', 'C', 'D'], -4, 3, 20, {
      rol: 'seftali',
      opaklik: 0.55,
      etiket: 'sol',
    }),
    ...otelenmisCokgen('sag', ['A', 'B', 'C', 'D'], 4, 3, 25, {
      rol: 'seftali',
      opaklik: 0.55,
      etiket: 'sağ',
    }),
    metin('yazi', -7, -7.5, '6 yüz: karşılıklı olanlar eş', 30, { rol: 'notr' }),
  ],
  adimlar: [
    adim(1, 'Kutuyu kesin', 'Kutuyu ayrıtlarından keserek yere serdiğinizde bu şekil çıkar. Buna açınım denir.', ['on', 'arka', 'ust', 'alt', 'sol', 'sag']),
    adim(2, 'Altı yüz', 'Ön, arka, üst, alt, sol, sağ. Toplam altı yüz.', ['yazi']),
    adim(3, 'Karşılıklılar eş', 'Ön ile arka aynı renkte ve aynı büyüklükte. Üst ile alt da öyle, sol ile sağ da.', ['on', 'arka', 'sol', 'sag']),
    adim(4, 'Katlayın', 'Bu şekli kesip katlarsanız kutu geri oluşur. Kutunun yüzey alanı, bu altı dikdörtgenin alanları toplamıdır.', ['ust', 'alt']),
  ],
}

const KOSE_KENAR = {
  slug: 'kose-ve-kenar-sayma',
  konuSlug: 's4-kose-ve-kenarlar',
  tur: 'kesif',
  baslik: 'Köşe ve kenar aynı sayıda',
  ozet:
    'Bir çokgende kaç kenar varsa o kadar köşe vardır. Köşe sayısını değiştirip kuralı sınayın.',
  zorluk: 2,
  sira: 1,
  durum: 'yayin',
  ayar: ayar('izgara', [-11, 8, 11, -8]),
  nesneler: [
    nokta('A', -8, -5, 0, { rol: 'lavanta' }),
    nokta('B', -2, -5, 1, { rol: 'lavanta' }),
    nokta('C', 1, 0, 2, { rol: 'lavanta' }),
    nokta('D', -4, 4, 3, { rol: 'lavanta' }),
    nokta('E', -9, 0, 4, { rol: 'lavanta' }),
    cokgen('besgen', ['A', 'B', 'C', 'D', 'E'], 5, { rol: 'nane', opaklik: 0.45 }),
    uzunluk('kAB', 'A', 'B', 6, { rol: 'gok', etiket: '1' }),
    uzunluk('kBC', 'B', 'C', 7, { rol: 'gok', etiket: '2' }),
    uzunluk('kCD', 'C', 'D', 8, { rol: 'gok', etiket: '3' }),
    uzunluk('kDE', 'D', 'E', 9, { rol: 'gok', etiket: '4' }),
    uzunluk('kEA', 'E', 'A', 10, { rol: 'gok', etiket: '5' }),
    olcumKaynakli('cevre', 'olcum_cevre', 'besgen', 11, { rol: 'lavanta' }),
    metin('yazi', 6, 6, '5 köşe → 5 kenar', 12, { rol: 'gul' }),
  ],
  adimlar: [
    adim(1, 'Köşeleri sayın', 'Beş mor nokta var; her biri bir köşe.', ['A', 'B', 'C', 'D', 'E']),
    adim(2, 'Kenarları sayın', 'Kenarlar 1’den 5’e numaralandı. Beş köşe, beş kenar.', ['kAB', 'kBC', 'kCD', 'kDE', 'kEA']),
    adim(3, 'Neden eşit?', 'Her kenar iki köşeyi birleştirir ve her köşede tam iki kenar birleşir. Bu yüzden sayıları hep eşittir.', ['yazi']),
    adim(4, 'Çevre', 'Beş kenarın uzunluklarını toplayın: çevreyi bulursunuz. Köşeleri sürükleyip kontrol edin.', ['cevre']),
  ],
}

const CEVRE4 = {
  slug: 'bahce-cevresi-olcme',
  konuSlug: 's4-cevre-olcme',
  tur: 'gercek_hayat',
  baslik: 'Bahçenin etrafına kaç metre tel gerekir?',
  ozet:
    'Bahçenin etrafını çevirmek için gereken tel, şeklin çevresi kadardır. Bahçeyi büyütüp küçültün.',
  zorluk: 3,
  sira: 1,
  durum: 'yayin',
  ayar: ayar('izgara', [-11, 8, 11, -8], { birim: 'metre' }),
  nesneler: [
    nokta('B1', -8, -5, 0, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('B3', 2, 2, 1, { rol: 'seftali', etiket: 'köşe' }),
    bilesen('B2', 'B3', 'B1', 2, { rol: 'notr', etiket: null, gorunur: false }),
    bilesen('B4', 'B1', 'B3', 3, { rol: 'notr', etiket: null, gorunur: false }),
    cokgen('bahce', ['B1', 'B2', 'B3', 'B4'], 4, { rol: 'nane', opaklik: 0.45, etiket: 'bahçe' }),
    uzunluk('en', 'B1', 'B2', 5, { rol: 'gok', etiket: 'en' }),
    uzunluk('boy', 'B2', 'B3', 6, { rol: 'gul', etiket: 'boy' }),
    olcumKaynakli('cevre', 'olcum_cevre', 'bahce', 7, { rol: 'lavanta' }),
    olcumKaynakli('alan', 'olcum_alan', 'bahce', 8, { rol: 'tereyagi' }),
  ],
  adimlar: [
    adim(1, 'En ve boy', 'Bahçenin iki ölçüsü var. Kutucukları sayarak da bulabilirsiniz.', ['en', 'boy']),
    adim(2, 'Tel için çevre', 'Etrafını çevirmek için dört kenarın toplamı kadar tel gerekir: (en + boy) × 2.', ['cevre']),
    adim(3, 'Çim için alan', 'Zemini kaplamak içinse alan gerekir: en × boy. Çevre ile alan farklı şeylerdir.', ['alan']),
    adim(4, 'Karıştırmayın', 'Bahçeyi büyütün: ikisi de büyüyor ama aynı hızda değil. Çevre metre, alan metrekare ile ölçülür.', ['cevre', 'alan']),
  ],
}

const ALAN_TAHMINI = {
  slug: 'kare-sayarak-alan',
  konuSlug: 's4-alan-tahmini',
  tur: 'kesif',
  baslik: 'Birim kareleri sayarak alan',
  ozet:
    'Şeklin kapladığı kutucukları sayın. Bulduğunuz sayı alandır. Eğik kenarlı şekillerde tam sayamayız, tahmin ederiz.',
  zorluk: 3,
  sira: 1,
  durum: 'yayin',
  ayar: ayar('izgara', [-11, 8, 11, -8]),
  nesneler: [
    nokta('D1', -9, -4, 0, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('D3', -3, 1, 1, { rol: 'nane', etiket: 'köşe' }),
    bilesen('D2', 'D3', 'D1', 2, { rol: 'notr', etiket: null, gorunur: false }),
    bilesen('D4', 'D1', 'D3', 3, { rol: 'notr', etiket: null, gorunur: false }),
    cokgen('dikdortgen', ['D1', 'D2', 'D3', 'D4'], 4, { rol: 'nane', opaklik: 0.45 }),
    olcumKaynakli('dikAlan', 'olcum_alan', 'dikdortgen', 5, { rol: 'nane' }),
    metin('dikAd', -6, -5.4, 'kutucukları say: tam', 6, { rol: 'nane' }),
    nokta('U1', 2, -4, 7, { surukleme: 'yok', rol: 'seftali', etiket: null }),
    nokta('U2', 9, -4, 8, { surukleme: 'yok', rol: 'seftali', etiket: null }),
    nokta('U3', 4, 3, 9, { rol: 'seftali', etiket: 'tepe' }),
    cokgen('ucgen', ['U1', 'U2', 'U3'], 10, { rol: 'seftali', opaklik: 0.45 }),
    olcumKaynakli('ucgenAlan', 'olcum_alan', 'ucgen', 11, { rol: 'seftali' }),
    metin('ucgenAd', 5.5, -5.4, 'eğik kenar: tahmin', 12, { rol: 'seftali' }),
  ],
  adimlar: [
    adim(1, 'Dikdörtgeni sayın', 'Yeşil şeklin içindeki kutucukları sayın. Sıra sayısı ile sütun sayısını çarparak da bulabilirsiniz.', ['dikdortgen', 'dikAlan']),
    adim(2, 'Ölçümle karşılaştırın', 'Saydığınız sayı ile ekrandaki alan aynı mı? Köşeyi sürükleyip birkaç kez deneyin.', ['dikAlan']),
    adim(3, 'Eğik kenar zor', 'Turuncu üçgende bazı kutucuklar yarım kalıyor. Tam kutucukları sayın, yarımları ikişer ikişer birleştirin.', ['ucgen']),
    adim(4, 'Tahmin ve ölçüm', 'Tahmininizi ekrandaki alanla karşılaştırın. Yakın çıkması yeter; alan tahmini böyle yapılır.', ['ucgenAlan']),
  ],
}

const ACI_DONME = {
  slug: 'aci-donme-miktari',
  konuSlug: 's4-aci-donme-miktari',
  tur: 'gercek_hayat',
  baslik: 'Açı, ne kadar döndüğümüzdür',
  ozet:
    'Bir kol sabit, diğeri dönüyor. Açı, kolun ne kadar döndüğünü söyler. Tam tur 360, yarım tur 180, çeyrek tur 90 derece.',
  zorluk: 3,
  sira: 1,
  durum: 'yayin',
  ayar: ayar('yok', [-10, 9, 10, -9]),
  nesneler: [
    nokta('O', 0, 0, 0, { surukleme: 'yok', rol: 'notr', etiket: 'dönme noktası' }),
    nokta('S', 7, 0, 1, { surukleme: 'yok', rol: 'gok', etiket: 'sabit kol' }),
    cizgi('sabitKol', 'dogru_parcasi', 'O', 'S', 2, { rol: 'gok', kalinlik: 5 }),
    cember('yorunge', 'O', 3, { uzerinde: 'S', rol: 'notr', kalinlik: 1, cizgiTipi: 'kesik' }),
    surgu('H', 'yorunge', 0, 7, 4, { rol: 'seftali', etiket: 'döndür' }),
    cizgi('donenKol', 'dogru_parcasi', 'O', 'H', 5, { rol: 'seftali', kalinlik: 5 }),
    aci('donmeAcisi', 'S', 'O', 'H', 6, { rol: 'tereyagi' }),
    metin('bilgi', 0, -8.2, 'çeyrek tur 90° — yarım tur 180° — tam tur 360°', 7, { rol: 'notr' }),
  ],
  adimlar: [
    adim(1, 'İki kol', 'Mavi kol sabit duruyor, turuncu kol dönüyor. Turuncu ucu sürükleyin.', ['sabitKol', 'donenKol']),
    adim(2, 'Çeyrek tur', 'Turuncu kolu tam yukarı getirin: açı 90 derece olur. Buna dik açı denir.', ['donmeAcisi']),
    adim(3, 'Yarım tur', 'Kolu mavinin tam tersine çevirin: 180 derece. İki kol düz bir çizgi oluşturur.', ['donmeAcisi']),
    adim(4, 'Tam tur', 'Dönmeye devam edip başladığınız yere gelirseniz 360 derece dönmüş olursunuz. Saat kolları da böyle döner.', ['donmeAcisi', 'bilgi']),
  ],
}

const ACI_CESITLERI = {
  slug: 'aci-cesitleri',
  konuSlug: 's4-aci-cesitleri',
  tur: 'kesif',
  baslik: 'Dar, dik, geniş, doğru açı',
  ozet:
    'Açının ölçüsü 90’dan küçükse dar, tam 90 ise dik, 90 ile 180 arasındaysa geniş, tam 180 ise doğru açıdır.',
  zorluk: 3,
  sira: 1,
  durum: 'yayin',
  ayar: ayar('yok', [-12, 8, 12, -8]),
  nesneler: [
    nokta('O1', -8, -3, 0, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('A1', -4, -3, 1, { surukleme: 'yok', rol: 'nane', etiket: null }),
    nokta('B1', -5.5, 0.5, 2, { surukleme: 'yok', rol: 'nane', etiket: null }),
    cizgi('d1a', 'dogru_parcasi', 'O1', 'A1', 3, { rol: 'nane', kalinlik: 4 }),
    cizgi('d1b', 'dogru_parcasi', 'O1', 'B1', 4, { rol: 'nane', kalinlik: 4 }),
    aci('dar', 'A1', 'O1', 'B1', 5, { rol: 'nane' }),
    metin('darAd', -6, -4.4, 'dar açı', 6, { rol: 'nane' }),
    nokta('O2', -1, -3, 7, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('A2', 3, -3, 8, { surukleme: 'yok', rol: 'gok', etiket: null }),
    nokta('B2', -1, 1, 9, { surukleme: 'yok', rol: 'gok', etiket: null }),
    cizgi('d2a', 'dogru_parcasi', 'O2', 'A2', 10, { rol: 'gok', kalinlik: 4 }),
    cizgi('d2b', 'dogru_parcasi', 'O2', 'B2', 11, { rol: 'gok', kalinlik: 4 }),
    aci('dik', 'A2', 'O2', 'B2', 12, { rol: 'gok' }),
    metin('dikAd', 1, -4.4, 'dik açı', 13, { rol: 'gok' }),
    nokta('O3', 6, -3, 14, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('A3', 10, -3, 15, { surukleme: 'yok', rol: 'seftali', etiket: null }),
    nokta('B3', 3.5, 0.5, 16, { surukleme: 'yok', rol: 'seftali', etiket: null }),
    cizgi('d3a', 'dogru_parcasi', 'O3', 'A3', 17, { rol: 'seftali', kalinlik: 4 }),
    cizgi('d3b', 'dogru_parcasi', 'O3', 'B3', 18, { rol: 'seftali', kalinlik: 4 }),
    aci('genis', 'A3', 'O3', 'B3', 19, { rol: 'seftali' }),
    metin('genisAd', 7.5, -4.4, 'geniş açı', 20, { rol: 'seftali' }),
    nokta('O4', 0, 5, 21, { surukleme: 'yok', rol: 'notr', etiket: null }),
    nokta('A4', 5, 5, 22, { surukleme: 'yok', rol: 'gul', etiket: null }),
    nokta('B4', -5, 5, 23, { surukleme: 'yok', rol: 'gul', etiket: null }),
    cizgi('d4a', 'dogru_parcasi', 'O4', 'A4', 24, { rol: 'gul', kalinlik: 4 }),
    cizgi('d4b', 'dogru_parcasi', 'O4', 'B4', 25, { rol: 'gul', kalinlik: 4 }),
    aci('dogruAci', 'A4', 'O4', 'B4', 26, { rol: 'gul' }),
    metin('dogruAd', 0, 6.4, 'doğru açı', 27, { rol: 'gul' }),
  ],
  adimlar: [
    adim(1, 'Dar açı', 'Ölçüsü 90 dereceden küçük olan açılara dar açı denir.', ['dar', 'darAd']),
    adim(2, 'Dik açı', 'Tam 90 derece olan açı dik açıdır. Kitap köşesi, duvar birleşimi hep dik açıdır.', ['dik', 'dikAd']),
    adim(3, 'Geniş açı', '90 ile 180 arasındaki açılara geniş açı denir.', ['genis', 'genisAd']),
    adim(4, 'Doğru açı', 'İki kol düz bir çizgi oluşturursa açı tam 180 derecedir; buna doğru açı denir.', ['dogruAci', 'dogruAd']),
  ],
}

const SIMETRI4 = {
  slug: 'dogruya-gore-simetri',
  konuSlug: 's4-dogruya-gore-simetri',
  tur: 'kesif',
  baslik: 'Doğruya göre simetri',
  ozet:
    'Simetri doğrusuna göre her nokta karşı tarafa aynı uzaklıkta geçer. Şekli sürükleyip uzaklıkların hep eşit kaldığını görün.',
  zorluk: 3,
  sira: 1,
  durum: 'yayin',
  ayar: ayar('izgara', [-11, 8, 11, -8]),
  nesneler: [
    nokta('E1', 0, -7, 0, { surukleme: 'yok', rol: 'gok', etiket: null }),
    nokta('E2', 0, 7, 1, { surukleme: 'yok', rol: 'gok', etiket: null }),
    cizgi('eksen', 'dogru', 'E1', 'E2', 2, { rol: 'gok', kalinlik: 3 }),
    nokta('A', -8, -4, 3, { rol: 'nane', etiket: 'A' }),
    nokta('B', -3, -4, 4, { rol: 'nane', etiket: 'B' }),
    nokta('C', -6, 3, 5, { rol: 'nane', etiket: 'C' }),
    cokgen('sekil', ['A', 'B', 'C'], 6, { rol: 'nane', opaklik: 0.5 }),
    yansima('goruntu', 'sekil', 'eksen', 7, { rol: 'gul', opaklik: 0.5 }),
    yansima('Ayansi', 'A', 'eksen', 8, { rol: 'gul', etiket: "A'" }),
    // Ayak sabit bir nokta olamaz: A yukari asagi tasininca dikmenin ayagi
    // da kayiyor, yoksa olculen sey artik eksene uzaklik olmuyor.
    izdusum('Ayak', 'A', 'eksen', 9, { rol: 'notr', etiket: null, gorunur: false }),
    uzunluk('solUzaklik', 'A', 'Ayak', 10, { rol: 'nane', etiket: 'A → eksen' }),
    uzunluk('sagUzaklik', 'Ayak', 'Ayansi', 11, { rol: 'gul', etiket: "eksen → A'" }),
  ],
  adimlar: [
    adim(1, 'Simetri doğrusu', 'Mavi dikey doğru simetri ekseni. Yeşil şeklin görüntüsü onun karşısında oluşuyor.', ['eksen', 'sekil', 'goruntu']),
    adim(2, 'Bir noktayı izleyin', 'A noktasının görüntüsü A′. İkisi eksenin iki yanında duruyor.', ['A', 'Ayansi']),
    adim(3, 'Uzaklıklar eşit', 'A’nın eksene uzaklığı ile A′’nın eksene uzaklığı aynı sayı. A’yı yukarı aşağı taşıyın: eşitlik bozulmuyor.', ['solUzaklik', 'sagUzaklik']),
    adim(4, 'Kural', 'Simetride her nokta, eksene dik doğrultuda aynı uzaklıkta karşıya geçer. Şekil aynı büyüklükte kalır, sadece yönü döner.', ['sekil', 'goruntu']),
  ],
}

const KODLAMA = {
  slug: 'geometrik-kodlama',
  konuSlug: 's4-geometrik-kodlama',
  tur: 'kesif',
  baslik: 'Adımlarla desen çizmek',
  ozet:
    'Aynı komutu tekrar tekrar uygularsak desen çıkar. Burada komut şu: "şekli 4 adım sağa taşı".',
  zorluk: 3,
  sira: 1,
  durum: 'yayin',
  ayar: ayar('izgara', [-13, 8, 13, -8]),
  nesneler: [
    nokta('A', -11, -4, 0, { rol: 'nane', etiket: null }),
    nokta('B', -8, -4, 1, { rol: 'nane', etiket: null }),
    nokta('C', -9.5, -1, 2, { rol: 'nane', etiket: 'sürükle' }),
    cokgen('motif', ['A', 'B', 'C'], 3, { rol: 'nane', opaklik: 0.6, etiket: 'başlangıç' }),
    ...otelenmisCokgen('adim1', ['A', 'B', 'C'], 4, 2, 4, { rol: 'gok', opaklik: 0.6 }),
    ...otelenmisCokgen('adim2', ['A', 'B', 'C'], 8, 4, 8, { rol: 'seftali', opaklik: 0.6 }),
    ...otelenmisCokgen('adim3', ['A', 'B', 'C'], 12, 6, 12, { rol: 'gul', opaklik: 0.6 }),
    ...otelenmisCokgen('adim4', ['A', 'B', 'C'], 16, 8, 16, { rol: 'tereyagi', opaklik: 0.6 }),
    metin('komut', -2, 6.6, 'komut: 4 sağa, 2 yukarı — 4 kez tekrarla', 20, { rol: 'notr' }),
    uzunluk('adimUzunlugu', 'A', 'adim1_A', 21, { rol: 'lavanta', etiket: 'bir adım' }),
  ],
  adimlar: [
    adim(1, 'Başlangıç şekli', 'Yeşil üçgen başlangıç. Köşesini sürükleyip biçimini değiştirebilirsiniz.', ['motif']),
    adim(2, 'Komutu bir kez uygulayın', 'Şekli 4 sağa, 2 yukarı taşıyın: mavi kopya çıkıyor.', ['adim1']),
    adim(3, 'Tekrarlayın', 'Aynı komut üç kez daha uygulandı. Her kopya bir öncekinden aynı kadar uzakta.', ['adim2', 'adim3', 'adim4', 'adimUzunlugu']),
    adim(4, 'Kodlama böyle çalışır', 'Bilgisayara "şunu yap, sonra tekrarla" demek yeterlidir. Tek bir komut düzenli bir desen üretiyor.', ['komut']),
  ],
}

/* ---------------------------------------------------------------- icerik */

const ORNEKLER = [
  {
    konuSlug: 's3-standart-sivi-olculeri',
    sahneSlug: 'litre-ve-mililitre',
    baslik: 'Markette litre okumak',
    hikaye:
      'Süt kutusunda 1 L, meyve suyunda 200 mL yazar. Litre büyük kapları, mililitre küçükleri ölçmek için kullanılır. 1 litre 1000 mililitredir; yani 200 mililitrelik beş kutu tam bir litre eder. İlaç şişelerinde ve tarif ölçülerinde de aynı birimler kullanılır.',
    soru: '200 mililitrelik kaç kutu meyve suyu 1 litre eder?',
    olcekAciklama: 'Her turuncu bardak 250 mililitredir.',
    kaynak: 'MEB kazanımı MAT.3.4 — standart sıvı ölçüleri',
    yasAraligi: '8-10',
  },
  {
    konuSlug: 's4-cevre-olcme',
    sahneSlug: 'bahce-cevresi-olcme',
    baslik: 'Tel çekmek mi, çim ekmek mi?',
    hikaye:
      'Bahçenin etrafına tel çekmek için çevreyi, zemine çim ekmek için alanı bilmek gerekir. İkisi farklı şeylerdir: çevre metre ile, alan metrekare ile ölçülür. Aynı çevreye sahip iki bahçenin alanları çok farklı olabilir — uzun ve ince bir bahçe ile kareye yakın bir bahçe aynı teli kullanır ama kareye yakın olanın alanı daha büyüktür.',
    soru: 'Eni 10, boyu 7 metre olan bahçenin etrafına kaç metre tel gerekir?',
    olcekAciklama: 'Izgaradaki 1 kutucuk 1 metredir.',
    kaynak: 'MEB kazanımı MAT.4.4 — çevre ölçme',
    yasAraligi: '9-11',
  },
  {
    konuSlug: 's4-cisimlerin-acinimi',
    sahneSlug: 'kutu-acinimi',
    baslik: 'Karton kutu tasarımı',
    hikaye:
      'Fabrikada kutular önce düz karton üzerine açınım olarak basılır, sonra kesilip katlanır. Tasarımcı, kartonu en az israfla kullanacak açınımı seçmek zorundadır. Kutunun yüzey alanı, açınımdaki bütün parçaların alanları toplamıdır; bu yüzden kutu tasarımı doğrudan maliyeti etkiler.',
    soru: 'Bir kutunun altı yüzü varsa ve karşılıklı yüzler eşse kaç farklı boyutta dikdörtgen vardır?',
    olcekAciklama: 'Izgaradaki 1 kutucuk 1 santimetredir.',
    kaynak: 'MEB kazanımı MAT.4.3 — cisimlerin açınımı',
    yasAraligi: '9-11',
  },
]

const SORULAR = [
  {
    konuSlug: 's3-geometrik-cisimlerin-ozellikleri',
    sahneSlug: 'kup-yuz-kose-ayrit',
    tip: 'sayisal',
    govde: 'Bir küpün kaç yüzü vardır?',
    cevap: { tip: 'sayisal', deger: 6, tolerans: 0 },
    ipucu: 'Açınımdaki kareleri sayın.',
    cozum: 'Küpün 6 yüzü, 8 köşesi ve 12 ayrıtı vardır.',
    zorluk: 1,
    puan: 1,
  },
  {
    konuSlug: 's3-geometrik-cisimlerin-ozellikleri',
    tip: 'sayisal',
    govde: 'Bir küpün kaç ayrıtı vardır?',
    cevap: { tip: 'sayisal', deger: 12, tolerans: 0 },
    ipucu: 'Altta 4, üstte 4, dikeyde 4.',
    cozum: '4 + 4 + 4 = 12 ayrıt.',
    zorluk: 2,
    puan: 2,
  },
  {
    konuSlug: 's3-sekilleri-kenar-sayisina-gore-siniflandirma',
    sahneSlug: 'kenar-sayisina-gore',
    tip: 'coktan_secmeli',
    govde: 'Altı kenarı olan şekle ne denir?',
    secenekler: ['Beşgen', 'Altıgen', 'Dörtgen', 'Üçgen'],
    cevap: { tip: 'coktan_secmeli', dogru: 1 },
    ipucu: 'Ad, kenar sayısından gelir.',
    cozum: 'Altı kenarlı şekle altıgen denir.',
    zorluk: 1,
    puan: 1,
  },
  {
    konuSlug: 's3-geometrik-cizim-araclari',
    sahneSlug: 'cetvel-ve-gonye',
    tip: 'coktan_secmeli',
    govde: 'Dik açı çizmek için hangi araç kullanılır?',
    secenekler: ['Pergel', 'Gönye', 'Silgi', 'Makas'],
    cevap: { tip: 'coktan_secmeli', dogru: 1 },
    ipucu: 'Gönyenin bir köşesi 90 derecedir.',
    cozum: 'Gönye dik açı çizmeye yarar. Cetvel uzunluk ölçer, pergel çember çizer.',
    zorluk: 1,
    puan: 1,
  },
  {
    konuSlug: 's3-cevre-uzunlugu',
    sahneSlug: 'cevre-uzunlugu-sayarak',
    tip: 'sayisal',
    govde: 'Eni 5, boyu 3 birim olan dikdörtgenin çevresi kaç birimdir?',
    cevap: { tip: 'sayisal', deger: 16, tolerans: 0, birim: 'birim' },
    ipucu: 'Dört kenarı toplayın.',
    cozum: '5 + 3 + 5 + 3 = 16 birim. Kısayol: (5 + 3) × 2 = 16.',
    zorluk: 2,
    puan: 2,
  },
  {
    konuSlug: 's3-simetri-dogrulari',
    sahneSlug: 'kac-simetri-dogrusu',
    tip: 'sayisal',
    govde: 'Bir karenin kaç simetri doğrusu vardır?',
    cevap: { tip: 'sayisal', deger: 4, tolerans: 0 },
    ipucu: 'Dikey, yatay ve köşegenler.',
    cozum: 'Karede 4 simetri doğrusu vardır: dikey, yatay ve iki köşegen.',
    zorluk: 2,
    puan: 2,
  },
  {
    konuSlug: 's3-simetri-dogrulari',
    tip: 'dogru_yanlis',
    govde: 'Dikdörtgenin köşegeni bir simetri doğrusudur.',
    cevap: { tip: 'dogru_yanlis', dogru: false },
    ipucu: 'Köşegenden katlarsanız iki yarı üst üste gelir mi?',
    cozum:
      'Dikdörtgenin köşegeninden katlarsanız yarılar çakışmaz. Dikdörtgenin sadece 2 simetri doğrusu vardır: dikey ve yatay.',
    zorluk: 3,
    puan: 2,
  },
  {
    konuSlug: 's3-standart-sivi-olculeri',
    sahneSlug: 'litre-ve-mililitre',
    tip: 'sayisal',
    govde: '200 mililitrelik kaç kutu meyve suyu 1 litre eder?',
    cevap: { tip: 'sayisal', deger: 5, tolerans: 0, birim: 'kutu' },
    ipucu: '1 litre 1000 mililitredir.',
    cozum: '1000 ÷ 200 = 5 kutu.',
    zorluk: 2,
    puan: 2,
  },
  {
    konuSlug: 's4-cisimlerin-acinimi',
    sahneSlug: 'kutu-acinimi',
    tip: 'sayisal',
    govde: 'Bir kutunun altı yüzü var ve karşılıklı yüzler eş. Kaç farklı boyutta dikdörtgen vardır?',
    cevap: { tip: 'sayisal', deger: 3, tolerans: 0 },
    ipucu: 'Ön-arka, üst-alt, sağ-sol.',
    cozum: 'Üç çift vardır: ön-arka, üst-alt, sağ-sol. Yani 3 farklı boyut.',
    zorluk: 3,
    puan: 3,
  },
  {
    konuSlug: 's4-kose-ve-kenarlar',
    sahneSlug: 'kose-ve-kenar-sayma',
    tip: 'dogru_yanlis',
    govde: 'Bir çokgende köşe sayısı ile kenar sayısı her zaman eşittir.',
    cevap: { tip: 'dogru_yanlis', dogru: true },
    ipucu: 'Sahnede beşgeni sayın.',
    cozum:
      'Her kenar iki köşeyi birleştirir ve her köşede iki kenar birleşir; bu yüzden sayıları hep eşittir.',
    zorluk: 2,
    puan: 2,
  },
  {
    konuSlug: 's4-cevre-olcme',
    sahneSlug: 'bahce-cevresi-olcme',
    tip: 'sayisal',
    govde: 'Eni 10, boyu 7 metre olan bahçenin etrafına kaç metre tel gerekir?',
    cevap: { tip: 'sayisal', deger: 34, tolerans: 0, birim: 'metre' },
    ipucu: '(en + boy) × 2.',
    cozum: '(10 + 7) × 2 = 34 metre tel gerekir.',
    zorluk: 2,
    puan: 2,
  },
  {
    konuSlug: 's4-alan-tahmini',
    sahneSlug: 'kare-sayarak-alan',
    tip: 'sayisal',
    govde: '6 sütun ve 5 satırdan oluşan bir dikdörtgende kaç birim kare vardır?',
    cevap: { tip: 'sayisal', deger: 30, tolerans: 0, birim: 'birim kare' },
    ipucu: 'Sütun sayısı ile satır sayısını çarpın.',
    cozum: '6 × 5 = 30 birim kare.',
    zorluk: 2,
    puan: 2,
  },
  {
    konuSlug: 's4-aci-donme-miktari',
    sahneSlug: 'aci-donme-miktari',
    tip: 'sayisal',
    govde: 'Çeyrek tur dönen bir kol kaç derece dönmüş olur?',
    cevap: { tip: 'sayisal', deger: 90, tolerans: 0, birim: 'derece' },
    ipucu: 'Tam tur 360 derece.',
    cozum: '360 ÷ 4 = 90 derece.',
    zorluk: 2,
    puan: 2,
  },
  {
    konuSlug: 's4-aci-cesitleri',
    sahneSlug: 'aci-cesitleri',
    tip: 'coktan_secmeli',
    govde: 'Ölçüsü 120 derece olan açı hangi çeşittir?',
    secenekler: ['Dar açı', 'Dik açı', 'Geniş açı', 'Doğru açı'],
    cevap: { tip: 'coktan_secmeli', dogru: 2 },
    ipucu: '90 ile 180 arasında.',
    cozum: '120 derece, 90 ile 180 arasında olduğu için geniş açıdır.',
    zorluk: 2,
    puan: 2,
  },
  {
    konuSlug: 's4-dogruya-gore-simetri',
    sahneSlug: 'dogruya-gore-simetri',
    tip: 'dogru_yanlis',
    govde: 'Simetri doğrusuna 3 birim uzaklıktaki bir noktanın görüntüsü de doğruya 3 birim uzaklıktadır.',
    cevap: { tip: 'dogru_yanlis', dogru: true },
    ipucu: 'Sahnedeki iki uzaklık ölçümünü karşılaştırın.',
    cozum: 'Simetride nokta, eksene dik doğrultuda aynı uzaklıkta karşıya geçer.',
    zorluk: 2,
    puan: 2,
  },
  {
    konuSlug: 's4-geometrik-kodlama',
    sahneSlug: 'geometrik-kodlama',
    tip: 'sayisal',
    govde:
      '"4 sağa, 2 yukarı" komutu 4 kez uygulanırsa şekil başlangıçtan kaç birim sağa gitmiş olur?',
    cevap: { tip: 'sayisal', deger: 16, tolerans: 0, birim: 'birim' },
    ipucu: 'Her adımda 4 birim.',
    cozum: '4 × 4 = 16 birim sağa gider. Yukarı ise 2 × 4 = 8 birim çıkar.',
    zorluk: 3,
    puan: 3,
  },
]

console.log('3. VE 4. SINIF GEOMETRI\n')
await uret(cagir, {
  sahneler: [
    KUP_ACINIM,
    KENAR_SAYISI,
    CIZIM_ARACLARI,
    CEVRE3,
    SIMETRI_DOGRULARI,
    LITRE,
    ACINIM4,
    KOSE_KENAR,
    CEVRE4,
    ALAN_TAHMINI,
    ACI_DONME,
    ACI_CESITLERI,
    SIMETRI4,
    KODLAMA,
  ],
  ornekler: ORNEKLER,
  sorular: SORULAR,
})

const rapor = JSON.parse(await cagir('kapsama_raporu'))
console.log('\nsahnesiz konu:', rapor.sahnesizKonuSayisi)

await istemci.close()
